version: '3.3'
volumes:
  static:
  media:
  pg_data:
  frontend_static:
services:

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    image: chew6acca/foodgram_backend
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    env_file:
      - .env
    image: chew6acca/foodgram_frontend
    volumes:
      - frontend_static:/app/result_build/
  nginx:
    image: nginx:1.19.3
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/frontend_static/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media/
      - static:/app/static_django/